name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.4.0
homepage: https://github.com/glynskyi/zefyrka

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  url_launcher: ^6.1.10
  quill_format: ^1.0.2
  font_awesome_flutter: ^10.4.0

  notus_format:
    git:
      url: https://github.com/tony-soft/notus_format.git
#      ref: a3a0c64339a1feb8bd1316334bbd0faf919660d4

  characters: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0