name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.6.0
homepage: https://github.com/glynskyi/zefyrka

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0

#  quill_format: ^1.0.2
  quill_format:
    git:
      url: https://github.com/tony-soft/quill_format.git
      ref: 621f198f265c5f5e798bd853e90c875d765a80c4

  notus_format:
    git:
      url: https://github.com/tony-soft/notus_format.git
      ref: 4addc6e14cd82a9126d097f732fd265cf0a72e25

  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
